### ISSUE TITLE
mismatch with paper

### ISSUE THREAD

**Issue by narutojxl** [wh200720041/iscloam#10]
Hi doctor wang,
* The current code doesn't include ` Temporal consistency check` module, right?
* `Geometrical consistency`, which calculate corner-to-corner and surf-to-surf with ceres to get constraint. Is there some reason, why not use FPFH first and ICP, have you test the performance between them?
* BTW, I tested  with our bag data, there is some missed loop detection.  I found there is a [LiDAR-Iris](https://github.com/BigMoWangying/LiDAR-Iris), maybe next we can test it, and then compare.

Thanks for your hard work and help!
Jiao

**Comment by wh200720041** [comment]
Hi @narutojxl 

There are some modifications based on the original paper. For practical consideration, some of the process is removed since it does not contribute too much to the overall performance. 

Yes, temporal consistency is removed. 
For geometrical consistency, using FPFH is slow. And ICP does not perform well. So I do not recommend this two approach. 

And Thanks for your mention on LiDAR-Iris. This is a good work.

Han

**Comment by narutojxl** [comment]
I see, thanks for your detailed reply @wh200720041 , closed it now :)
Best
Jiao

**Comment by YangSiri** [comment]
Hi, @wh200720041 

Thanks for your great work and clear codes. I noticed the input _/velodyne_points_ is already intensity-calibrated instead of the original one, right? So I wonder how you do it? Is there any specific instruction besides the paper you mentioned?

**Comment by LiShuaixin** [comment]
Hi @wh200720041, thanks for your contribution and sharing of your code.
I'm interested in the calibration of Lidar intensity. Lots of works have been presented for the terrestrial laser scanner (TLS) which is used to sense the environment in stationary and can generate dense point cloud, but few for the Lidar. The only calibration approach I found in the literatures is the one referred in your paper, but it doesn't give a deep instruction. 
I noticed that @YangSiri has the same issue, would you mind give some tips on this problem? Many thanks!
