### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by pcarrascof** [wh200720041/iscloam#14]
Hi, I'm using ROS Melodic an download the repository with git clone.
When I did "catkin_make" the error said that I had to use "catkin_make_isolated".
And after doing so the error says: / usr / bin / ld: cannot find -lBoost :: timer

Could you help me?

**Comment by wh200720041** [comment]
Hi @pcarrascof 

Did you install libboost?

You can install libboost by
`sudo apt-get install libboost-all-dev`

Han

**Comment by pcarrascof** [comment]
Yes, I have libboost installed

**Comment by gyzou** [comment]
I had the same issue, and hand-fixed the cmake.

@wh200720041 What GTSAM version are you using?

**Comment by AN-Ahmed** [comment]
I have the same issue, how did you fix it?

**Comment by wh200720041** [comment]
Hi 

I have done some test on the GTSAM 4.0.3. The problem happens on the newer GTSAM version. I version I used is GTSAM 3.x so I did not find this issue

The problem is probably caused by an update from 4.0.2 to 4.0.3 according to the gtsam 
[https://github.com/borglab/gtsam/pull/303](url)

The solution is to insert 
find_package(Boost REQUIRED COMPONENTS timer thread)
to Cmakelists. 

The cmakelists.txt is also updated.
