### ISSUE TITLE
FLOAM vs ISCLOAM

### ISSUE THREAD

**Issue by cgbcgb** [wh200720041/iscloam#3]
Hey，I have a question，why your FLOAM（lidar odometry only） is better than your  ISCLOAM（with loop closure）in KITTI test dataset（sequence 11 ～ 21）？

**Comment by wh200720041** [comment]
Actually, the result of isc-loam is better than floam if you compare the trajectory with ground truth. However, the way KITTI dataset estimates trajectory is a little bit different. They collect short term odometer instead of long term, so that loop closure does not contribute to the result. You may check their website for the source code of odometry evaluation. In the meanwhile, there is some parameter change in the floam.

**Comment by cgbcgb** [comment]
> Actually, the result of isc-loam is better than floam if you compare the trajectory with ground truth. However, the way KITTI dataset estimates trajectory is a little bit different. They collect short term odometer instead of long term, so that loop closure does not contribute to the result. You may check their website for the source code of odometry evaluation. In the meanwhile, there is some parameter change in the floam.

You means that the evaluation method of KITTI can't quantitatively evaluate the real translation or rotation error correctly ?

**Comment by wh200720041** [comment]
Note that on KITTI website
From all test sequences, our evaluation computes translational and rotational errors for all possible subsequences of length (100,...,800) meters.

The odometry is estimated locally

**Comment by cgbcgb** [comment]
> Note that on KITTI website
> From all test sequences, our evaluation computes translational and rotational errors for all possible subsequences of length (100,...,800) meters.
> 
> The odometry is estimated locally

OK，I got it, Thanks ^_^

**Comment by cgbcgb** [comment]
I noticed your ISC-LOAM has been improved greatly on the KITTI test dataset.
Would you like to share your main improvements ？

**Comment by caoyifeng001** [comment]
请问，你们用的计算精度的工具是哪个吗
