### ISSUE TITLE
Sharing the newest improvements?

### ISSUE THREAD

**Issue by sunrainljy** [wh200720041/iscloam#4]
On the KITTI benchmark, I noticed your ISC-LOAM has been improved greatly.
Would you like to share your main improvements ？Thanks for your good work!

**Comment by cgbcgb** [comment]
> On the KITTI benchmark, I noticed your ISC-LOAM has been improved greatly.
> Would you like to share your main improvements ？Thanks for your good work!

王晗老哥太赞了，paper都已经中了ICRA，还在提高算法的精度，真不是混paper拿学位的，为真正的学术精神手动点赞

**Comment by wh200720041** [comment]
Hi sunrainljy:

I think I made some mistakes during the first submission because I didn't check my data carefully before submission. After that I looked into problem and fixed some bug in my code. The core mathematics remains same.

In the meanwhile, there are some parameters change as well. I will make some updates on the code. 

Regards
Han

**Comment by sunrainljy** [comment]
Thanks a lot for the sharing. I will try the elegent code later.
